package fl.core.wsclient.calc.echo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "Echo", targetNamespace = "http://ws.calc.fl/")
@XmlSeeAlso({ ObjectFactory.class })
public interface Echo {

    /**
     * 
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://ws.calc.fl/", className = "fl.core.wsclient.calc.echo.Echo_Type")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://ws.calc.fl/", className = "fl.core.wsclient.calc.echo.EchoResponse")
    @Action(input = "http://ws.calc.fl/Echo/echoRequest", output = "http://ws.calc.fl/Echo/echoResponse")
    public String echo(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     * 
     * @param arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "howManyMonkeys", targetNamespace = "http://ws.calc.fl/", className = "fl.core.wsclient.calc.echo.HowManyMonkeys")
    @ResponseWrapper(localName = "howManyMonkeysResponse", targetNamespace = "http://ws.calc.fl/", className = "fl.core.wsclient.calc.echo.HowManyMonkeysResponse")
    @Action(input = "http://ws.calc.fl/Echo/howManyMonkeysRequest", output = "http://ws.calc.fl/Echo/howManyMonkeysResponse")
    public int howManyMonkeys(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
