package fl.core.wsclient.calc.echo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "Repeater", targetNamespace = "http://ws.calc.fl/", wsdlLocation = "http://localhost:8014/service/echo?wsdl")
public class Repeater extends Service {

    private final static URL REPEATER_WSDL_LOCATION;
    private final static WebServiceException REPEATER_EXCEPTION;
    private final static QName REPEATER_QNAME = new QName("http://ws.calc.fl/", "Repeater");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8014/service/echo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPEATER_WSDL_LOCATION = url;
        REPEATER_EXCEPTION = e;
    }

    public Repeater() {
        super(__getWsdlLocation(), REPEATER_QNAME);
    }

    public Repeater(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPEATER_QNAME, features);
    }

    public Repeater(URL wsdlLocation) {
        super(wsdlLocation, REPEATER_QNAME);
    }

    public Repeater(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPEATER_QNAME, features);
    }

    public Repeater(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Repeater(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns Echo
     */
    @WebEndpoint(name = "EchoImplPort")
    public Echo getEchoImplPort() {
        return super.getPort(new QName("http://ws.calc.fl/", "EchoImplPort"), Echo.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns Echo
     */
    @WebEndpoint(name = "EchoImplPort")
    public Echo getEchoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.calc.fl/", "EchoImplPort"), Echo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPEATER_EXCEPTION != null) {
            throw REPEATER_EXCEPTION;
        }
        return REPEATER_WSDL_LOCATION;
    }

}
